### ISSUE TITLE
Text.offScreenCanvas issues

### ISSUE THREAD

**Issue by wpernath** [melonjs/melonJS#1113]
#### OS platform / Browser  
Mac OS 12.4 / Chrome 103
 
#### melonJS version 
12.0.0

#### Bug description  
I am using several Text objects to display a HUD in my game. If I am using Text.offScreenCanvas = true, I get Exceptions upon onDestroyEvent() of the stage (as soon as I call game.world.removeChild()):

Stacktrace:
melonjs.module.js:36288 Uncaught TypeError: Cannot read properties of undefined (reading 'canvas')
    at ScoreItem.onDeactivateEvent (melonjs.module.js:36288:53)
    at HUDContainer.removeChildNow (melonjs.module.js:18064:17)
    at HUDContainer.reset (melonjs.module.js:17537:16)
    at HUDContainer.destroy (melonjs.module.js:18315:12)
    at World.removeChildNow (melonjs.module.js:18078:21)
    at World.deferredRemove (melonjs.module.js:17361:8) 

As soon as I use the "ScoreItem" without offScreenCanvas = true, there is no such exception. 

#### Steps to reproduce the bug
Link to the full game source code: https://github.com/wpernath/grumpycat-melonjs

Source code can be found in src/js/stage/hud/hud-container.js

#### Console log Extract 
to show possible exception/errors raised by the engine or the browser

##### How to enable/use the console log
* Webkit (Chrome, Safari) : https://developer.chrome.com/devtools
* Opera : http://www.opera.com/dragonfly/documentation/
* FireFox : http://getfirebug.com/enable
* MS (Edge) : https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/debugger

**Comment by obiot** [comment]
Hi @wpernath, thanks for the report.  Not sure how this one did not show up before (maybe a regression) but nevertheless it's all fixed and will be part of the 13.0 version that I hope to publish after the weekend (I am myself waiting for a bug fix in the doc parser/generator so that I can publish the whole thing !)

This said using Text is generally a really bad idea together with WebGL (using the offScreenCanvas option makes it a bit better performance wise, but then it generates individual texture for each of them), so you should really consider using BitmapText instead if you are working on a high performance game or have a lots of graphical assets already. Else you can always force the Canvas rendering mode if you prefer to stick with Text (just use `renderer : me.video.CANVAS` when calling video.init), I did not see your game, but based not the screenshot here, they will definitely look the same both in Canvas and WebGL, but it's up to you, and I did not see your game running :)

Oh, and once your game is done, we would love you to come and share about it on our showcase channel on discord : https://discord.com/channels/608636676461428758/957462243023396874

**Comment by obiot** [comment]
(and closing this one since it's fixed in the coming release)

**Comment by wpernath** [comment]
Hi @obiot, Thanks a lot for the quick fix! And for the advice as well! After reading how proportional fonts are being displayed in WebGL, I decided to go with BitmapText's in the game. -- I was already wondering why my poor laptop was producing noise like a helicopter, as soon as the MENU was displayed anyway. ;-) But with your hint it got quite clear.

I'd love to come and share about the game after it's finished. Thank you for inviting me.
